In [ ]:
'''1.What is a Python library? Why we use Python libraries?'''
'''Python library is a collection of codes or module of codes that uses to do specific operations in python program. Python libraries are used
because we no need to rewrite the code again  and we will make use of the code which is already available.'''

In [ ]:
'''2.What is the difference between Numpy array and List'''
'''Numpy arrays are homogeneous and will allow only data with a data type. List is hetrogeneous and will allow data with different data types.
 Arrays will take less time to access than list.Arrays will give fast computation in numpy.'''

In [7]:
'''3. Find the shape, size and dimension of the following array?

[[1, 2, 3, 4]

[5, 6, 7, 8],

[9, 10, 11, 12]]'''

import numpy as np
n = np.array([[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]])
print("shape of array", n.shape)
print("size of array", n.size)
print("Dimension of array", n.ndim)

shape of array (3, 4)
size of array 12
Dimension of array 2


In [8]:
'''4. Write python code to access the first row of the following array?

[[1, 2, 3, 4]

[5, 6, 7, 8],

[9, 10, 11, 12]]'''
import numpy as np
arr3 = np.array([[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]])
print("First row of array",arr3[0])


First row of array [1 2 3 4]


In [10]:
'''5. How to you access the element at the third row and fourth column from the given numpy array?

[[1, 2, 3, 4]

[5, 6, 7, 8],

[9, 10, 11, 12]]'''

import numpy as np
arr4 = np.array([[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]])
print("Array element is", arr4[2][3])

Array element is 12


In [12]:
'''6. Write code to extract all odd indexed elements from the given numpy array?

[[1, 2, 3, 4]

[5, 6, 7, 8],

[9, 10, 11, 12]]'''

import numpy as np
arr5 = np.array([[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]])
print("Array elements with odd index is", arr5[arr5%2!=0])

Array elements with odd index is [ 1  3  5  7  9 11]


In [15]:
'''7. How can you generate a random 3x3 matrix with values between 0 and 1?'''
import numpy as np
result = np.random.rand(3,3)
print(result)

[[0.08279419 0.86056407 0.00165528]
 [0.78771911 0.19710087 0.32890566]
 [0.28179648 0.29088213 0.90253274]]


In [ ]:
'''8. Describe the difference between np.random.rand and np.random.randn?'''

'''np.random function will generate values between 0 and 1. Rand will return the numbers from uniform disrtribution in interval of (0,1). Randn will return the 
numbers from normal distribution with mean of 0 and varaince of 1. '''

In [21]:
'''
9. Write code to increase the dimension of the following array?

[[1, 2, 3, 4]

[5, 6, 7, 8],

[9, 10, 11, 12]]'''

import numpy as np
arr7 = np.array([[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]])
arr8 = np.expand_dims(arr7, axis = 0)
print("After increasing the dimension of array", arr8)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
After increasing the dimension of array [[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]]


In [26]:
'''10. How to transpose the following array in NumPy?

[[1, 2, 3, 4]

[5, 6, 7, 8],

[9, 10, 11, 12]]'''
import numpy as np
arr9 = np.array([[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]])
print("Transpose of matrix ", arr9.T)

Transpose of matrix  [[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]


In [38]:
'''11. Consi^er the following matrix:

Matrix A2 [[1, 2, 3, 4] [5, 6, 7, 8],[9, 10, 11, 12]]

Matrix B2 [[1, 2, 3, 4] [5, 6, 7, 8],[9, 10, 11, 12]]'''

import numpy as np

A2 = np.array([[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]])
B2 = np.array([[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]])
'''Perform the following operation using Python
1. Index wise multiplication'''
print(A2 * B2)
'''2. Matrix multiplication'''
A3 = np.array([[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]])
B4 = np.array([[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12], [1,2,3,4]])
print(np.dot(A3,B4))
'''3. Add both the matrics'''
print(A2 + B2)
'''4. Subtract matrix B from A'''
print(B2 - A2)
'''5.Divide Matrix B by A'''
print(B2/A2)

[[  1   4   9  16]
 [ 25  36  49  64]
 [ 81 100 121 144]]
[[ 42  52  62  72]
 [106 132 158 184]
 [170 212 254 296]]
[[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]]
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [42]:
'''12.Which function in Numpy can be used to swap the byte order of an array?'''
import numpy as np
arr1 = np.array([1,256,100],dtype='int16')
print(arr1.byteswap(True))

[  256     1 25600]


In [44]:
'''13.  What is the significance of the np.linalg.inv function?'''

import numpy as np

A2 = np.array([[1, 2],[5, 6]])
print(np.linalg.inv(A2))

[[-1.5   0.5 ]
 [ 1.25 -0.25]]


In [50]:
'''14.What does the np.reshape function do, and how is it used?'''

'''numpy reshape function will actually rearrange the elements in the given order'''

A5 = np.array([[1, 2],[5, 6],[9, 10]])

print(A5.reshape(2,3))

[[ 1  2  5]
 [ 6  9 10]]


In [53]:
'''15. What is broadcasting in Numpy?'''

'''Broadcasting will happen with a scalar value.It will happen whem any kind og matrix airthmetic operations are happening between two arrays 
with different dimensions.'''

import numpy as np

A = np.array([1,2,3,4])

B = 4

print(A+B)

[5 6 7 8]
